import { Inter } from "next/font/google";
import AdminNavbar from "@/components/AdminNavbar";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
    title: "Layouts - Admin",
    description: "Generated by create next app",
};

export default function AdminLayout({ children }) {
    return (
        <div>
            <AdminNavbar />
            {children}
        </div>
    );
}
