import React from 'react'

const contact = () => {
  return (
    <div>
      This is contact page
    </div>
  )
}

export default contact

export const metadata = {
  title: "New App - Contact",
  description: "Generated by create next app",
};
