import React from 'react'

const about = () => {
  return (
    <div>
      This is about page
    </div>
  )
}

export default about

export const metadata = {
  title: "New App - About",
  description: "Generated by create next app",
};
